config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :messages, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show 
  post   '/like/:post_id' ,to: 'likes#like',   as: 'like'
  delete '/like/:post_id' ,to: 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '赤虫' },
    { id: 3, name: '白サシ' },
    { id: 4, name: '紅サシ' },
    { id: 5, name: 'チーズ白サシ' },
    { id: 6, name: 'チーズ紅サシ' },
    { id: 7, name: '本ラビット' },
    { id: 8, name: '特ラビット' },
    { id: 9, name: 'ラビットウォーム' },
    { id: 10, name: 'ワカサギウォーム' },
    { id: 11, name: 'ぶどう虫' },
    { id: 12, name: '秘密' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :text, presence: true
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '金山' },
    { id: 3, name: '早稲沢' },
    { id: 4, name: '桧原本村' },
    { id: 5, name: '堂場岬' },
    { id: 6, name: '馬の首' },
    { id: 7, name: '野鳥の森新橋下' },
    { id: 8, name: '孤鷹森' },
    { id: 9, name: '中之島' },
    { id: 10, name: '細野' },
    { id: 11, name: '月島' },
    { id: 12, name: '白樺' },
    { id: 13, name: 'いかり潟' },
    { id: 14, name: 'ホテル下' },
    { id: 15, name: 'いかり肩' },
    { id: 16, name: '大石' },
    { id: 17, name: 'G目黒前' },
    { id: 18, name: '雄子沢' },
    { id: 19, name: '京ヶ森' },
    { id: 20, name: '温泉下' },
    { id: 21, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  with_options extend ActiveHash::Associations::ActiveRecordExtensions do
    belongs_to :place
    belongs_to :water_depth
    belongs_to :weather
    belongs_to :feed
  end

  def was_attached?
    image.attached?
  end

  validates :fishing_result, presence: true
  validates :title, presence: true, unless: :was_attached?

  with_options numericality: { other_than: 1 } do
    validates :place_id
    validates :water_depth_id
    validates :weather_id
    validates :feed_id
  end

  def self.sort(selection)
    case selection
    when 'fishing_result_desc'
      all.order(fishing_result: :DESC)
    when 'likes_count_desc'
      all.order(likes_count: :DESC)
    when 'created_at_desc'
      all.order(created_at: :DESC)
    when 'created_at_asc'
      all.order(created_at: :ASC)
    else
      all.order(created_at: :DESC)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  validates :nickname, :skill, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字(半角)と数字(半角)の両方を含めて設定してください'
end

app/models/water_depth.rb
class WaterDepth < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1~3m' },
    { id: 3, name: '4~6m' },
    { id: 4, name: '7~9m' },
    { id: 5, name: '10~12m' },
    { id: 6, name: '13~15m' },
    { id: 7, name: '16~18m' },
    { id: 8, name: '19~21m' },
    { id: 9, name: '22~24m' },
    { id: 10, name: '25~27m' },
    { id: 11, name: '28~30m' },
    { id: 12, name: '秘密' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/weather.rb
class Weather < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '晴れ' },
    { id: 3, name: '曇り' },
    { id: 4, name: '雨' },
    { id: 5, name: '雪' },
    { id: 6, name: '吹雪' },
    { id: 7, name: '大雨' },
    { id: 8, name: '強風' },
    { id: 9, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :skill])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    ActionCable.server.broadcast 'message_channel', content: @message if @message.save
  end

  private

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @message = Message.new
    @messages = @post.messages.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to root_path if @post.user_id != current_user.id
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
      redirect_to root_path
    else
      redirect_to action: :index
    end
  end

  def search
    @posts = Post.sort(params[:keyword])
  end

  private

  def post_params
    params.require(:post).permit(:title, :post_text, :fishing_result, :place_id, :water_depth_id, :weather_id, :feed_id,
                                 :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @fishing_result_sum = Post.where(user_id: @user.id).sum(:fishing_result)
    @max_fishing_result = Post.where(user_id: @user.id).maximum(:fishing_result)
    @max_fishing_result_details = Post.find_by fishing_result: @max_fishing_result, user_id: @user.id
    @posts = @user.posts.includes(:user).order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ワカサギ釣果情報サイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://mplus-fonts.sourceforge.jp/webfonts/general-j/mplus_webfonts.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= post.id %>">
<% if user_signed_in? %>
    <% if current_user.likes.find_by(post_id: post.id) %>
      <%= link_to unlike_path(post.id), method: :delete, remote: true do %>
          <div class = "iine__button">❤️<%= post.likes.count %></div>
      <% end %>
    <% else %>
      <%= link_to like_path(post.id), method: :post, remote: true do %>
          <div class = "iine__button">♡️<%= post.likes.count %></div>
      <% end %>
    <% end %>
  <% else %>
    <div class = "iine__button">❤️<%= post.likes.count %></div>
<% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/posts/edit.html.erb
<div class="post-contents">  
  <div class="post-main">
    <h2 class="post-main-title">釣果情報を入力</h2>
    <%= form_with model:@post,local: true do |f| %>

      <%#= render 'shared/error_messages', model: f.object %>

      <%# 出品画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          出品画像
        </div>
        <div class="click-upload">
          <p>
            画像をアップロード
          </p>
          <%= f.file_field :image, id:"post-image" %>
        </div>
      </div>
      <%# /出品画像 %>
      <%# 商品名と商品説明 %>
      <div class="new-posts">
        <div class="weight-bold-text">
          投稿タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"例）爆釣の一日！", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            説明文
          </div>
          <%= f.text_area :post_text, class:"items-text", id:"item-info", placeholder:"例）浅場の強さで朝方は爆釣！日中も食いが止まらなかった！" ,rows:"7" ,maxlength:"1000" %>
        </div>
        <div class="weight-bold-text">
          釣果
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :fishing_result, class:"items-text", id:"item-name", placeholder:"半角数字のみを入力" %>
      </div>

      <div class="post-detail">
        <div class="form">
          <div class="weight-bold-text">
            釣り場
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:place_id, Place.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
          <div class="weight-bold-text">
            棚（水面から○○m）
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:water_depth_id, WaterDepth.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
          <div class="weight-bold-text">
            天気
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:weather_id, Weather.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
          <div class="weight-bold-text">
            エサ
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:feed_id, Feed.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        </div>
      </div>

      <div class="post-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<main class="main">
  <%# トップ画 %>
  <div class="top">
    <div class="card__wrapper">
      <div class="main_image">
        <div class="bxslider">
          <div><%= image_tag "img4.jpg" %></div>
          <div><%= image_tag "img1.jpg" %></div>
          <div><%= image_tag "img2.jpg" %></div>
          <div><%= image_tag "img3.jpg" %></div>
          <div><%= image_tag "img5.jpg" %></div>
          <div><%= image_tag "img6.jpg" %></div>
          <div><%= image_tag "img7.jpg" %></div>
          <div><%= image_tag "img11.jpg" %></div>
          <div><%= image_tag "img12.jpg" %></div>
        </div>
      </div>
    </div>
  </div>
  <%# /トップ画 %>
 
  <div class="wakasagi-contents">
    <%# 投稿一覧 %>
    <div class="post_contents">
      <div class="post_wrap" id="4">
        <h2 class="title">
          釣果情報一覧
        </h2>
        <div class="search">
          <div class="search_box">
            <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.select :keyword, [["---選択してください---", "first"],["釣れた順", "fishing_result_desc"], 
                                      ["いいね数順", "likes_count_desc"], 
                                      ["新着順", "created_at_desc"], 
                                      ["投稿が古い順", "created_at_asc"]] %>
            <%= form.submit "並び替える", class: "search-btn" %>
            <% end %> 
          </div>
        </div>
        <ul class='post-lists'>
          <% @posts.each do |post|%>
          <li class='list'>
            <%= link_to post_path(post.id) do %>
             <div class="img_wrap">
                <%= image_tag post.image, class: "post-img" if post.image.attached?%>
                <% unless post.image.present? %>
                <div class='post-img'>
                  <%= image_tag "image7.png", class: "item-img" %>
                </div>
                <% end %>
              </div>
              <div class='post-info'>
                <%= link_to "#{post.user.nickname}さん",  user_path(post.user.id), class: "post_user_name"%>
                <span class="sukima"><%= post.created_at.strftime('%Y/%m/%d') %></span>
                <div class='result'>
                  <%= "釣果：#{post.fishing_result}匹" %>               
                </div>
                <div class="info_header">
                  <div class="message_txt">&#x1f4ac;
                  <%= "#{Message.where(post_id:post.id).count}" %>
                  </div>
                  <div class="like_txt">
                  <%= render partial: 'likes/like', locals: {post: post} %>
                  </div>
                </div>                    
              </div> 
            <% end %>         
          </li>
          <% end %>

          <% if @posts.length == 0  %>
            <li class='list'>
              <%= link_to '/' do %>
                <%= image_tag "image7.png", class: "item-img" %>
                <div class='item-info'>
                  <h3 class='item-name'>
                    投稿してね！
                  </h3>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%# /投稿一覧部分 %>

  <%# アイテム紹介 %>

    <div class="item_wrap" id="2">
      <h2 class="title">
        アイテム紹介
      </h2>
      <ul class='item-lists'>
      </ul>
    </div>
    <%# /アイテム紹介 %>

    <%# よくある質問 %>
    <div class="faq_wrap" id="3">
      <h2 class="title">
        よくある質問
      </h2>
      <ul class='faq-lists'>
      </ul>
    </div>
    <%# /よくある質問 %>

    <%# 桧原湖マップ %>
    <div class="map_wrap" id="1">
      <h2 class="title">
        桧原湖マップ
      </h2>
      <div class="map_box">
        <input id="address" type="textbox" value="場所の名前を入力">
        <input type="button" value="地図を検索" onclick="codeAddress()">
        <div id="display">緯度,経度(37.6831667,140.0590371)</div>
        <div id='map'>
        </div>
        <script>
        let map

        function initMap(){
          geocoder = new google.maps.Geocoder()

          map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 37.6831667, lng:140.0590371},
            zoom: 13,
          });

          marker = new google.maps.Marker({
            position:  {lat: 40.7828, lng:-73.9653},
            map: map
          });
        }

        let geocoder

        function codeAddress(){
          let inputAddress = document.getElementById('address').value;

          geocoder.geocode( { 'address': inputAddress}, function(results, status) {
            if (status == 'OK') {
              map.setCenter(results[0].geometry.location);
              var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location
              });
              display.textContent = "検索結果：" + results[ 0 ].geometry.location
            } else {
              alert('該当する結果がありませんでした：' + status);
            }
          });   
        }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHqUkfEeMRFVEgs2xV6K0sQXjroMU533c&callback=initMap" async defer></script>
      </div>
    </div>
    <%# /桧原湖マップ %>
  </div>
<div id="page_top"><a href="#"></a></div>
</main>
<%= render "shared/footer" %>

app/views/posts/search.html.erb
<div class="search-contents">
  <div class="search-header">
    <%= link_to "戻る", root_path, class: "nav__btn" %>
  </div>
  <div class="post_wrap">
    <h2 class="title">
      釣果情報一覧
    </h2>
    <div class="search">
      <div class="search_box">
        <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.select :keyword, [["---選択してください---", "first"],["釣れた順", "fishing_result_desc"], 
                                    ["いいね数順", "likes_count_desc"], 
                                    ["新着順", "created_at_desc"], 
                                    ["投稿が古い順", "created_at_asc"]] %>
          <%= form.submit "並び替える", class: "search-btn" %>
        <% end %> 
      </div>
    </div>
      <ul class='post-lists'>
        <% @posts.each do |post|%>
        <li class='list'>
          <%= link_to post_path(post.id) do %>
            <div class="img_wrap">
              <%= image_tag post.image, class: "post-img" if post.image.attached?%>
              <% unless post.image.present? %>
              <div class='post-img'>
                <%= image_tag "image7.png", class: "item-img" %>
              </div>
              <% end %>
            </div>
            <div class='post-info'>
              <%= link_to "#{post.user.nickname}さん",  user_path(post.user.id)%>
              <span class="sukima"><%= post.created_at.strftime('%Y/%m/%d') %></span>
              <div class='result'>
                <%= "釣果：#{post.fishing_result}匹" %>               
              </div>
              <div class="info_header">
                <div class="message_txt">&#x1f4ac;
                <%= "#{Message.where(post_id:post.id).count}" %>
                </div>
                <div class="like_txt">
                <%= render partial: 'likes/like', locals: {post: post} %>
                </div>
              </div>                    
            </div> 
          <% end %>         
        </li>
        <% end %>

        <% if @posts.length == 0  %>
          <li class='list'>
            <%= link_to '/' do %>
              <%= image_tag "image7.png", class: "item-img" %>
              <div class='item-info'>
                <h3 class='item-name'>
                  投稿してね！
                </h3>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-show">
  <div class="post-box">
    <%= link_to "戻る", root_path, class: "nav__btn" %>
    <br><%= link_to "#{@post.user.nickname}さん",  user_path(@post.user.id),class: "name"%>
    <div class="box-header-right">        
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <%= link_to "削除", post_path(@post.id), method: :delete, class: "nav__btn" %>
        <%= link_to "編集", edit_post_path(@post.id), class: "nav__btn" %>
      <% end %>
    </div>
    <div class="item-img-content">
      <%= image_tag @post.image  if @post.image.attached?%>
        <% unless @post.image.present? %>
          <div class='temporary-img'>
          <%= image_tag "image7.png", class: "item-img" %>
          </div>
        <% end %>
    </div>

    <div class="info_header-show">
      <div class="message_txt">&#x1f4ac;
      <%= "#{Message.where(post_id:@post.id).count}" %>
      </div>
      <div class="like_txt">
      <%= render partial: 'likes/like', locals: {post: @post} %>
      </div>
      <div><%= @post.created_at.strftime('%Y/%m/%d') %></div>
    </div>
             
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-post">投稿タイトル</th>
          <td class="detail-value"><%= @post.title %></td>
        </tr>
        <tr>
          <th class="detail-post">釣果</th>
          <td class="detail-value"><%= "#{@post.fishing_result}匹" %></td>
        </tr>
        <tr>
          <th class="detail-post">釣り場</th>
          <td class="detail-value"><%= @post.place.name %></td>
        </tr>
        <tr>
          <th class="detail-post">棚</th>
          <td class="detail-value"><%= "水面から#{@post.water_depth.name}付近" %></td>
        </tr>
        <tr>
          <th class="detail-post">天気</th>
          <td class="detail-value"><%= @post.weather.name %></td>
        </tr>
        <tr>
          <th class="detail-post">エサ</th>
          <td class="detail-value"><%= @post.feed.name %></td>
        </tr>
        <tr>
          <%if @post.post_text.present? %>
          <th class="detail-post">説明文</th>
          <td class="detail-value"><%= @post.post_text  %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  
    <div class = "message-box">
      <%= form_with model: [@post,@message], class: "message_form" do |f| %>
        <%= f.text_field :text, placeholder:"コメントする", maxlength:"40",class: "message_form_box" %>
        <%= f.submit '投稿する',class: "message_form_btn" %>
      <% end %>
      ＜コメント一覧＞
      <div id='messages'>
        <% @messages.reverse_each do |message| %>
          <div class="message_text">
            <p><%= link_to "#{message.user.nickname}さん",  user_path(message.user.id), class: "message_name"%>
            <span class="message_text_sukima"><%= l message.created_at %></span>
            <br><%= message.text %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
    <footer class="footer">
      <p class="copyright">Copyright © WATANABE SHOYA All rights reserved.</p>
    </footer>

app/views/shared/_header.html.erb
<div class="small_header">
  <div class="small_header_wrap">
    <div class="hamburger">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <nav class="globalMenuSp">
        <% if user_signed_in? %>
          <ul>
              <li><%= link_to "投稿する", new_post_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <li><a href="https://www.urabandai-inf.com/">桧原湖周辺情報</a></li>
          </ul>
        <% else %>
          <ul>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><a href="https://www.urabandai-inf.com/">桧原湖周辺情報</a></li>
          </ul>
        <% end %>
    </nav>
    <%= link_to "ワカサギ釣果情報サイト＜桧原湖版＞", root_path ,class: "greeting_small"%>
  </div>
</div>




    <header class="header">
      <div class="inner">
        <div class="nav">          
          <% if user_signed_in? %>
            <div class="nav__left">
              <div class = "greeting">
              <%= link_to "こんにちは#{current_user.nickname}さん！", root_path ,class: "greeting"%>
              </div>
            </div>
          <% else %>
            <div class="nav__left">
              <%= link_to "ワカサギ釣果情報サイト＜桧原湖版＞", root_path ,class: "greeting"%>
            </div>
          <% end %>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "nav__btn"%>
              <%= link_to "投稿する", new_post_path, class: "nav__btn" %>
              <%= link_to "マイページ", user_path(current_user.id), class: "nav__btn" %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: "nav__btn" %>
              <%= link_to "新規登録", new_user_registration_path, class: "nav__btn" %>
            </div>
          <% end %>

        </div>
      </div>
      <nav id="global_nav">
        <div class="gnav_cnt">
          <div class="gnav_menu">
            <ul class="gnav_list">
              <li class="item">
                <a href="#1" class="gnav_btn">
                <span class="gnav_title">桧原湖マップ</span>
                </a>
              </li>
              <li class="item">
                <a href="#2" class="gnav_btn">
                <span class="gnav_title">アイテム紹介</span>
                </a>
              </li>
              <li class="item">
                <a href="#3" class="gnav_btn">
                <span class="gnav_title">よくある質問</span>
                </a>
              </li>
              <li class="item">
                <a href="https://www.urabandai-inf.com/" class="gnav_btn">
                <span class="gnav_title">桧原湖周辺情報</span>
                </a>
              </li>
              <li class="item">
                <a href="#4" class="gnav_btn">
                <span class="gnav_title">釣果情報</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>